# Site settings
title: Desenvolvedores
email:
description: Dicas, tutoriais, opiniões e compartilhamento de conhecimento para desenvolvedores
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://douglasgabriel.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
image_posts_default: /img/HNCK4530.jpg

# Build settings
markdown: kramdown
