# Site settings
title: Douglas Gabriel
email: douglasxgabriel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Analista de Sistema e das coisas da vida. Partilhando um pouco do que sei ou
  do que acho que sei.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://douglasgabriel.github.io" # the base hostname & protocol for your site
twitter_username: douglasxgabrie1
github_username:  douglasgabriel
image_posts_default: /img/background-header.jpg
key_words: blog, thinks, development, pensamentos, desenvolvimento

# Build settings
markdown: kramdown
