# Site settings
title: Douglas Gabriel
email: douglasxgabriel@gmail.com
description: Desenvolvedor Full-Stack, com especialidade em aplicações Java e tecnologias Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://douglasgabriel.github.io" # the base hostname & protocol for your site
github_username:  douglasgabriel
linkedin_username:  douglasggouveia
image_posts_default: /img/me.jpg

# Build settings
markdown: kramdown
